### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by yuvalabou**
Following PEP8 import rules.
Docstring cleanup
Format the code using psf-black code formatter for better readability

### CODE REVIEW

**Comment by rt400** [comment]
@yuvalabou Hi,
thanks for your check.. i can't see the how to merge your changes ??

**Comment by yuvalabou** [comment]
I know, by mistake I have opened the pull request on the wrong repo. If you mind I will pull request on the main integration "shabat-holidays".

**Comment by rt400** [comment]
you mean https://github.com/rt400/Jewish-Sabbaths-Holidays ?

**Comment by yuvalabou** [comment]
Yes, just made a pull request there.
Thank you

**Pull request closed without merging**
